// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfSmWXOimR22HMVe6hliOCNs6ZDRzk79E',
    appId: '1:419419890925:android:dca24aa2b0d204377c58e4',
    messagingSenderId: '419419890925',
    projectId: 'green-wall-561af',
    databaseURL: 'https://green-wall-561af-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'green-wall-561af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKdr0WzhurqYcPJCgKezoSI43DqKDwYw0',
    appId: '1:419419890925:ios:de402be91b192e8e7c58e4',
    messagingSenderId: '419419890925',
    projectId: 'green-wall-561af',
    databaseURL: 'https://green-wall-561af-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'green-wall-561af.appspot.com',
    iosClientId: '419419890925-g0staf5e423grtdnuqsb5f2qr8l191la.apps.googleusercontent.com',
    iosBundleId: 'com.example.greenMaster',
  );
}
